require("dashboard").setup({
	theme = "doom",
	config = {
		header = {
			"                                       ",
			"                                       ",
			"                                       ",
			"                                       ",
			"                                       ",
			"                                       ",
			"                                       ",
			"                                       ",
			"              ▄ ▄                      ",
			"          ▄   ▄▄▄     ▄ ▄▄▄ ▄ ▄        ",
			"          █ ▄ █▄█ ▄▄▄ █ █▄█ █ █        ",
			"       ▄▄ █▄█▄▄▄█ █▄█▄█▄▄█▄▄█ █        ",
			"     ▄ █▄▄█ ▄ ▄▄ ▄█ ▄▄▄▄▄▄▄▄▄▄▄▄▄▄     ",
			"     █▄▄▄▄ ▄▄▄ █ ▄ ▄▄▄ ▄ ▄▄▄ ▄ ▄ █ ▄   ",
			"   ▄ █ █▄█ █▄█ █ █ █▄█ █ █▄█ ▄▄▄ █ █   ",
			"   █▄█ ▄ █▄▄█▄▄█ █ ▄▄█ █ ▄ █ █▄█▄█ █   ",
			"       █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█ █▄█▄▄▄█       ",
			"                                       ",
			"                                       ",
			"                                       ",
			"                                       ",
			"                                       ",
			"                                       ",
			"                                       ",
			"                                       ",
			"                                       ",
		},
		center = {
			{
				icon = " ",
				icon_hl = "Title",
				desc = "Recent Files           ",
				desc_hl = "String",
				key = "SPC s s",
				keymap = "",
				key_hl = "Number",
				action = "",
			},
			{
				icon = " ",
				icon_hl = "Title",
				desc = "Find File           ",
				desc_hl = "String",
				key = "SPC s f",
				keymap = "",
				key_hl = "Number",
				action = "",
			},
			{
				icon = " ",
				icon_hl = "Title",
				desc = "Toggle Tree           ",
				desc_hl = "String",
				key = "SPC t t",
				keymap = "",
				key_hl = "Number",
				action = "",
			},
			{
				icon = " ",
				icon_hl = "Title",
				desc = "Dark Mode             ",
				desc_hl = "String",
				key = "SPC  m d",
				keymap = "",
				key_hl = "Number",
				action = "",
			},
			{
				icon = " ",
				icon_hl = "Title",
				desc = "Light Mode           ",
				desc_hl = "String",
				key = "SPC m l",
				keymap = "",
				key_hl = "Number",
				action = "",
			},
		},
		footer = {},
	},
})
